name: test-package
on: [push]


jobs:

  test-package:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Install build package
        run: pip install build
      
      - name: Build package
        run: python -m build $GITHUB_WORKSPACE
      
      - name: Install package
        run: pip install $GITHUB_WORKSPACE

      - name: Run package with sample PCAP files
        run: python $GITHUB_WORKSPACE/.ci_scripts/run-all-pcaps.py
